version: "3.2"
services:
    apache1:
      image: apache_ssl 
      container_name: apache_alt_php_ssl1
      hostname: apache_alt_php_ssl
      volumes:
        - ./server:/var/www/html
        - ./apache2:/etc/apache2/
      depends_on: 
          - ldap1
      ports:
          - "443:443"
          - "8080:80"
      networks:
        - ldap_network_ssl      

    ldap1:
      image: osixia/openldap:latest
      container_name: ldap_with_ssl1
      hostname: ldap_ssl1
      ports: 
        - "389:389"
        - "636:636"
      volumes:
        - ./data/certificates:/container/service/slapd/assets/certs
        - ./data/slapd/database:/var/lib/ldap
        - ./data/slapd/config:/etc/ldap/slapd.d
      environment: 
        - LDAP_ORGANISATION=mariusInc
        - LDAP_DOMAIN=marius.com
        - LDAP_ADMIN_USERNAME=admin
        - LDAP_ADMIN_PASSWORD=admin_pass
        - LDAP_CONFIG_PASSWORD=config_pass
        - "LDAP_BASE_DN=dc=marius,dc=com"
        - LDAP_TLS_CRT_FILENAME=server.crt
        - LDAP_TLS_KEY_FILENAME=server.key
        - LDAP_TLS_CA_CRT_FILENAME=marius.com.ca.crt
        - LDAP_READONLY_USER=true
        - LDAP_READONLY_USER_USERNAME=user-ro
        - LDAP_READONLY_USER_PASSWORD=ro_pass
      networks:
        - ldap_network_ssl 

    ldapdmin1:
      image: osixia/phpldapadmin:latest
      container_name: phpldapadmin1
      hostname: phpldapadmin
      ports: 
        - "80:80"
      environment: 
        - PHPLDAPADMIN_LDAP_HOSTS=ldap_ssl1
        - PHPLDAPADMIN_HTTPS=false
      depends_on:
        - ldap1
      networks:
        - ldap_network_ssl

networks:
    ldap_network_ssl:
      driver: bridge
    
    
   
  
  
