version: "3.2"
services:
    apache:
      image: php:8.0-apache
      container_name: apache_ldap 
      volumes:
        - ./fmd:/var/www/html
        - ./docker_apache/conf_pwd/:/usr/local/apache2/
        - ./docker_apache/etc_apache2/:/etc/apache2/
      ports:
        - '8082:80'
        - '443:443'
      networks:
      - openldap
     # restart: unless-stopped

    ldap:
      image: osixia/openldap
      container_name: ldap-service
      ports:
        - 389:389
        - 636:636
      restart: unless-stopped
      environment:
        - LDAP_ORGANISATION=marius fmd
        - LDAP_DOMAIN=mariusberinde.com
        - LDAP_BASE_DN=mariusberinde.com
        - LDAP_ADMIN_PASSWORD=admin
        - LDAP_CONFIG_PASSWORD=config
      networks:
      - openldap


    ldapdmin:
      image: osixia/phpldapadmin
      container_name: phpldapadmin
      
      ports:
        - 8443:443
        - 8080:80
      environment:
        - PHPLDAPADMIN_LDAP_HOSTS=ldap-service
      networks:
      - openldap
     # restart: unless-stopped
  
    phpldapadmin:
      image: osixia/phpldapadmin:latest
      container_name: phpldapadmin
      hostname: phpldapadmin
      ports: 
        - "80:80"
      environment: 
        - PHPLDAPADMIN_LDAP_HOSTS=openldap
        - PHPLDAPADMIN_HTTPS=false
      depends_on:
        - ldap
      networks:
        - openldap
      
networks:
  openldap:
    driver: bridge
  default:
    name: ldap_network



    