version: '3.9'
services:
  apache:
    image: apache_ssl #httpd:latest
    container_name: es2_cert
    ports:
    - '8094:80'
    - '8095:443'
    volumes:
    - ./html:/var/www/html
  #  - ./html:/usr/local/apache2/htdocs
    - ./apache2:/etc/apache2

# /etc/apache2